### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by exihuatl** [devongovett/atom-jade#32] opened 2015-04-04 14:03 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (C:\Users\Renia\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:565:9)
<unknown> (C:\Users\Renia\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:187:43)
```

**Comment by thefivetoes** [comment] 2015-04-06 12:53
This is a duplicate of: https://github.com/devongovett/atom-jade/issues/30

**Comment by LinusU** [comment] 2015-04-14 07:56
Fixed in 0.4.0

**Closed by LinusU** 2015-04-14 07:56 UTC
