### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by anonymous-penguin** [devongovett/atom-jade#41] opened 2015-04-11 22:50 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (C:\Users\**********\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:550:9)
<unknown> (C:\Users\**********\AppData\Local\atom\app-0.190.0\resources\app\src\package.js:172:43)
```

**Comment by LinusU** [comment] 2015-04-13 14:46
Dupe of #30

**Comment by LinusU** [comment] 2015-04-14 07:56
Fixed in 0.4.0

**Closed by LinusU** 2015-04-14 07:56 UTC
