### ISSUE TITLE
Bracket text incorrectly highlighted

### ISSUE THREAD

**Issue by msmaili** [devongovett/atom-jade#54] opened 2015-07-09 00:07 UTC
Please see the below screenshot:

![sample](https://cloud.githubusercontent.com/assets/4451986/8585206/b58074ba-2593-11e5-8846-b3b81db10243.png)

`hello` is being colored like an html element when it's supposed to just be treated as plain text.

**Comment by LinusU** [comment] 2015-07-09 07:18
Duplicate of #28

**Closed by LinusU** 2015-07-09 07:18 UTC
Labels: duplicate
