### ISSUE TITLE
Conflict with removeTrailingWhitespace

### ISSUE THREAD

**Issue by FuriouZz** [devongovett/atom-jade#48] opened 2015-06-09 13:37 UTC
The `removeTrailingWhitespace` is not working when I use your syntax highlighting.

**Comment by LinusU** [comment] 2015-06-09 13:41
Please use the search field before reporting new issues. This is a duplicate of #21.

> Re. the issue: The whitespace package has deliberately chosen to ignore jade files and I don't think that we should overrule their decision. See atom/whitespace#46 and atom/whitespace#52.

**Closed by LinusU** 2015-06-09 13:41 UTC
